In [125]:
import pandas as pd
import numpy as np


In [3]:
pd.__version__

'2.3.1'

In [4]:
car_df = pd.read_csv("data/car_fuel_efficiency.csv")

In [8]:
car_df.shape

(9704, 11)

In [9]:
car_df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [19]:
car_df.groupby('fuel_type').size()

fuel_type
Diesel      4806
Gasoline    4898
dtype: int64

In [35]:
car_df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [36]:
#count number of non-zeros - as is.null().sum() will return number of missing values per column
(car_df.isnull().sum()!=0).sum()

np.int64(4)

In [42]:
car_df.fuel_efficiency_mpg.describe()

count    9704.000000
mean       14.985243
std         2.556468
min         6.200971
25%        13.267459
50%        15.006037
75%        16.707965
max        25.967222
Name: fuel_efficiency_mpg, dtype: float64

In [52]:
car_df[car_df.origin == 'Asia'].fuel_efficiency_mpg.max()


np.float64(23.759122836520497)

In [63]:
horsepower_median_before_na=car_df.horsepower.median()
horsepower_median_before_na

np.float64(149.0)

In [81]:
#most freq value for horsepower
horsepower_most_freq=car_df.horsepower.mode()[0]
horsepower_most_freq

np.float64(152.0)

In [76]:
horsepower_vals = car_df.horsepower
len(horsepower_vals)

9704

In [69]:
horsepower_vals.isna().sum()

np.int64(708)

In [83]:
horsepower_vals = horsepower_vals.fillna(horsepower_most_freq)

In [84]:
horsepower_vals.median()

np.float64(152.0)

In [86]:
horsepower_vals.median() > horsepower_median_before_na

np.True_

In [166]:
X=car_df[(car_df.origin == 'Asia')][['vehicle_weight','model_year']][0:7]
X

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [167]:
X=np.array(X)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [168]:
XTX_1 = X.dot(X.T)
XTX_1

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [169]:
XTX_2 = X.T.dot(X)
XTX_2

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [170]:
XTX_2.shape

(2, 2)

In [173]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
len(y)

7

In [175]:
w=(np.linalg.inv(XTX_2).dot(X.T)).dot(y)
w

array([0.01386421, 0.5049067 ])

In [176]:
sum(w)

np.float64(0.5187709081074016)